# Generated by Django 3.0 on 2020-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
    ]
